### ISSUE TITLE
Not getting changes tracked?

### ISSUE THREAD

**Issue by RobertLaverick** [thepirat000/Audit.NET#10]
Hey, I've been trying today to get a combination of Audit.NET SqlServer and EF tracking changes to my database. I'm getting events to fire, but I'm not able to get any changes to be tracked? Instead I seem to get an empty list in my DB.

Is there anything in particular I need to know?

I'm configured with OptOut, and AnyContext - and my DbContext is an extension of AuditContext. I get the new state of the object perfectly fine, but no information on changes that have been made.

**Comment by thepirat000** [comment]
Can you share a minimal code that behaves like that so I can investigate further

**Comment by thepirat000** [comment]
Could you try with the latest version?
This is probably related to Bug #11

**Comment by RobertLaverick** [comment]
![image](https://cloud.githubusercontent.com/assets/10117445/20301526/8599a35c-ab1b-11e6-88a3-bb09462a0ba2.png)

![image](https://cloud.githubusercontent.com/assets/10117445/20301571/bbd7cfd4-ab1b-11e6-8c11-5a69f4c99c9c.png)


I've tried with the latest version, I had no luck and it seems the changes field does not like what I'm doing.

As you can see in the first image, I'm attaching an edited model, and witht the second, a simple enough EF/SQL/Audit.NET setup.

When I tried using your code snippet (nice feature Btw), it showed that I was indeed getting an empty list of Changes, even with the 4.6 code.

Is there a problem with the fact I'm attaching a model?

**Comment by thepirat000** [comment]
Will take a look and add some unit test for the attaching model, honestly I've never tested the attaching.

**Comment by thepirat000** [comment]
Ok. I know what's the i.

The problem is reproducible only on the full framework version (EF6)

And is because of the behavior of the attach. As stated [here](https://msdn.microsoft.com/en-us/library/jj592677(v=vs.113).aspx#Anchor_0)

> The original value is the value that the property had when the entity was queried from the database **or attached to the context**

So if you're attaching an entity with its final property values (you don't change the properties after attaching), Audit.EF library will not be able to detect changes because it will compare the `CurrentValue` and `OriginalValue` but they will be always the same (the value when the entity was attached). 

Will try to see if I can provide a generic solution that works for attached entities, but have in mind that in any case, the library will provide the `OriginalValue` as the property value when the entity was attached.

**Comment by thepirat000** [comment]
Hi.

I've changed the way the library detect changes, so it will now include all the columns for Attach+ChangeState behavior.

Please check with the latest version (v.4.6.1)

Note you'll get the `OriginalValue` as the object property value when the entity *was attached*. 

From [MSDN](https://msdn.microsoft.com/en-us/library/jj592676(v=vs.113).aspx): 

> When you change the state to Modified all the properties of the entity will be marked as modified and all the property values will be sent to the database when SaveChanges is called.

I think this is the most the library can do for such cases.
