### ISSUE TITLE
MongoDB Dataprovider Date serialization

### ISSUE THREAD

**Issue by EngelenH** [thepirat000/Audit.NET#114]
StartDate and EndDate are both serialized as strings for me. Not as (utc) DateTimes as shown in the nosql for mongo screenshot. This of course makes some things quite difficult later on if you want to correlate events and they are saved as strings with a time zone component (i.e. 2018-01-01T01:00:00:00.0000000+02:00).

You would have to load the entire collection and normalize all events to a common timezone or UTC before you could determine their order.

**Comment by thepirat000** [comment]
Oh you're totally right, sorry. Dates should be saved as Bson Dates but are being stored as strings :( will provide a fix for this. 
This is because we do like `eventBson = Bson.Parse(Json.Serialize(auditEvent))` I think we can use a `JavaScriptDateTimeConverter` from JSON.NET so the Bson.Parse correctly detects the dates as dates.

**Comment by thepirat000** [comment]
This was fixed on version 11.2.0, now the .NET DateTimes are stored as MongoDB DateTime by default. 

Feel free to re-open if you're still having problems.
