### ISSUE TITLE
Audit.EntityFramework packages depend of SqlServer

### ISSUE THREAD

**Issue by Deilan** [thepirat000/Audit.NET#141]
`Audit.EntityFramework` and `Audit.EntityFramework.Core` packages depend of `Microsoft.EntityFrameworkCore.SqlServer` and `Microsoft.EntityFrameworkCore.SqlServer.Design`. That's confusing. What if a client uses a different provider? Will the lib work for his lib/app? Why he has to ship SQL Server-specific packages within his lib/app?

**Comment by thepirat000** [comment]
Yeah, it is confusing, but the library `Microsoft.EntityFrameworkCore.SqlServer` is used [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/DbContextHelper.Core.cs#L51) and [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/DbContextHelper.Core.cs#L147) to access the data annotations in order to get the real Table and Column names. It works with other providers like SQLite, returning the correct names, so it should not represent a problem other than having the word "SqlServer" on its name.

Nevertheless I'm noticing the `Microsoft.EntityFrameworkCore.SqlServer.Design` is not needed at all, so I will remove that reference in the next version.

**Comment by thepirat000** [comment]
Note the new version does not include the reference to `Microsoft.EntityFrameworkCore.SqlServer.Design`

https://www.nuget.org/packages/Audit.entityframework/

I'm closing this, but if you are still having problems, you can add a comment here and I'll re-open the issue and take a look.

**Comment by Deilan** [comment]
> Microsoft.EntityFrameworkCore.SqlServer is only used here and here to access the data annotations in order to get the real Table and Column names.

@thepirat000 It looks like these snippets could also work if `SqlServer()` would be replaced with `Relational()`. Take a look at the corresponding [PR](https://github.com/thepirat000/Audit.NET/pull/145).

**Comment by thepirat000** [comment]
Merged and Fixed on v.12.3.2, thanks!
