### ISSUE TITLE
How to filter properties based on attributes

### ISSUE THREAD

**Issue by biju-ps** [thepirat000/Audit.NET#144]
Hi 
Thanks for the great library !!
Is there any way to log filtered fields only . That is only fields with *certain attributes* or something ?
I my case, need to log only critical properties. Any help would be appreciated

**Comment by thepirat000** [comment]
Can you explain a little bit more about your use case? Are you auditing webapi? entity framework?
also have you seen the Custom Action documentation? you can change the output there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thepirat000** [comment]
For the Custom Action example check this issue https://github.com/thepirat000/Audit.NET/issues/113 and the docs [here](https://github.com/thepirat000/Audit.NET#custom-actions).

Also nota that on WebApi you can ignore controllers, methods and parameters with `AuditIgnoreAttribute`, check [this](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#audit-ignore-attribute)

**Comment by thepirat000** [comment]
Actually, if you rely on JSON.NET for serializing the Audit Events (what is done by default), you can ignore properties with [JsonIgnore attribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonIgnoreAttribute.htm)

**Comment by biju-ps** [comment]
> Actually, if you rely on JSON.NET for serializing the Audit Events (what is done by default), you can ignore properties with JsonIgnore attribute

Can't use JsonIgnore because I am using the serialized json with full properties for other purpose 
A custom property solely for auditing will be more useful

**Comment by thepirat000** [comment]
I think it's not easy to implement something like that working for any case, since there are multiple sources for the information included on the audit events. 

The serialization is not _always_ handled by the Audit.NET library itself. But for the objects directly serialized by the library, you could implement a [JSON.NET Contract Resolver](https://www.newtonsoft.com/json/help/html/ContractResolver.htm) that ignores properties with a custom attribute, and then set it as the Audit.NET's default JSON settings. For example:

```
Audit.Core.Configuration.JsonSettings = new JsonSerializerSettings
{
    ContractResolver = new AuditIgnoreAttributeResolver()
};
```

```
public class AuditIgnoreAttributeResolver : DefaultContractResolver
{
    protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
    {
        IList<JsonProperty> props = base.CreateProperties(type, memberSerialization);
        foreach (var prop in props)
        {
            prop.Ignored = type.GetProperty(prop.UnderlyingName).GetCustomAttribute<CustomIgnoreAttribute>() != null;
        }
        return props;
    }
}
```

But it will not work for example for the **Request Body** field of an action method, because it's read directly from the HttpContext stream as a string.
