### ISSUE TITLE
[AuditOverride] for Audit.WebApi

### ISSUE THREAD

**Issue by KlebersonLeite** [thepirat000/Audit.NET#164]
Is it possible?

**Comment by thepirat000** [comment]
I think it's possible, at least it makes more sense than the "ignore" attribute because ignoring a property means not including it on the output, which depends on the serialization method...

But this option would require to reflect over the entire audit event graph for each event, and it will have a direct impact on performance, even if you are not using the attribute at all.. So maybe this feature should be optional and disabled by default

**Comment by thepirat000** [comment]
Nevertheless I think implementing this in a generic way, would require a very complex process.

Will need to walk the properties in nested objects, indexed properties, arrays... It would need to have error handling, loop detection logic, all with the performance impact of the heavy use of reflection. 

At the end if you care about how the objects are serialized, you can use all the power of JSON.NET (Contract Resolvers, JsonConverters) or implement your own Audit DataProvider.
