### ISSUE TITLE
Missing strong name

### ISSUE THREAD

**Issue by B-Virtual** [thepirat000/Audit.NET#18]
Hi,

Would it be possible to strongly sign your release version that you package in your Nuget Package. This way the nuget can also be used in projects that require all assemblies to be signed. Make sure you make a wise decision on your key because if you change it in future versions other issues come up for backwards compatibility.

Kind regards,
Bjorn

**Comment by thepirat000** [comment]
Will probably work on this soon, but will provide different NuGet packages for Strongly Named versions.

**Comment by thepirat000** [comment]
For compatibility, I've created a Strong Name version of each package (except for Audit.NET.MongoDB since the MongoDB driver is not signed).
Use the new packages ending with ".StrongName":

[Audit.NET.StrongName](https://www.nuget.org/packages/Audit.NET.StrongName)
[Audit.NET.AzureDocumentDB.StrongName](https://www.nuget.org/packages/Audit.NET.AzureDocumentDB.StrongName)
[Audit.NET.AzureStorage.StrongName](https://www.nuget.org/packages/Audit.NET.AzureStorage.StrongName)
[Audit.NET.SqlServer.StrongName](https://www.nuget.org/packages/Audit.NET.SqlServer.StrongName)
[Audit.EntityFramework.StrongName](https://www.nuget.org/packages/Audit.EntityFramework.StrongName)
[Audit.DynamicProxy.StrongName](https://www.nuget.org/packages/Audit.DynamicProxy.StrongName)
[Audit.Mvc.StrongName](https://www.nuget.org/packages/Audit.Mvc.StrongName)
[Audit.Wcf.StrongName](https://www.nuget.org/packages/Audit.Wcf.StrongName)
[Audit.WebApi.StrongName](https://www.nuget.org/packages/Audit.WebApi.StrongName)
