### ISSUE TITLE
Fluent Property Ignores Don't Work on Interfaces or Inherited Classes

### ISSUE THREAD

**Issue by iamwyza** [thepirat000/Audit.NET#186]
**Describe the bug**
If you a base class, or interface, that describes columns for entities, then use the Fluent interface to ignore properties in that class, it won't ignore them.  Using attributes will.

**To Reproduce**
For the entity:

```csharp
public class MyTest {
      public string MyField { get;set;}
}

public class MyInheritedEntity : MyTest {

}
```
And the configuration
```csharp
Configuration.Setup().ForContext<ApplicationDbContext>(config =>
                    config.ForEntity<MyTest>(x => x
                        .Ignore(y => y.MyField)
                    )
           );
```

The field MyField will be included in the changes even though it should not be.

**Expected behavior**
MyField should not be included in the changes section.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 14.0.1

**Comment by thepirat000** [comment]
Hi. Some clarifications.

- It will not work with interfaces because interfaces are not _inherited_, they are _implemented_, so the attributes will not be inherited by the implementer. Only in the case of base abstract classes, the attributes on the properties can be inherited (you can check this [post](https://bradwilson.typepad.com/blog/2011/08/interface-attributes-class-attributes.html)).

- The fluent API `ForEntity<T>` method will **only** apply for the specific `T` and not to its derived types. So you will need to call the method for each derived class you want to audit. 

Note that what you are asking for (being able to use the fluent API on the base types) can probably be implemented, but I think it would strongly affect the performance because it will need to use reflection each time for each property, without the possibility of an effective cache.

Anyway if you have any idea on how to implement this kind of things, I'm totally open to hear your comments.

Regards

**Comment by iamwyza** [comment]
For type caching, what if the first time, it checked to see if the type is assignable from the basetype.  If it is, then parse the rules for the base type, and cache the rules for the original type that was checked.  It would still be a bit more work up front, it's true, but after the first time, it should be fine.  May have to add another fluent extension to specifically say that it's a inheritable type that should be used to scan against.

Psuedo Code: (not exactly like this, but something in this general vein)

```csharp 
Type type = entity.GetType();
if (cache.containsKey(type)) return cache[type];

if (hasRulesFor(type))
      addToCache(type, rulesFor(type));

foreach(Type baseType in GetFluentBaseTypes()) {
    if (type.IsAssignableFrom(baseType)) {
         mergeToCache(type, rulesFor(baseType));
    }
}
```

```csharp
Configuration.Setup().ForContext<ApplicationDbContext>(config =>
                    config.ForBaseEntity<MyTest>(x => x
                        .Ignore(y => y.MyField)
                    )
           );
```

**Comment by thepirat000** [comment]
Problem is that it should be recursive because the parent could have a parent, and so on. Also you need to impose a precedence order in case more than one implementation of the same property has multiple annotations

**Comment by thepirat000** [comment]
I still don't feel this is something worth implementing.

The entity classes (in your case the derived classes) can be configured explicitly one by one, just like you do for EF or any other ORM framework. I see no advantage in providing such mechanism (inheritance and precendence of property attributes) for classes that just represents entities in a relational database.

Still open to validate and eventually merge any pull request you want to contribute.

Regards

**Comment by iamwyza** [comment]
I can see the reasons why this would add alot of extra bulk to the project.  Thanks for thinking it through and considering it.
