### ISSUE TITLE
How to modify the EventType value on DB changes?

### ISSUE THREAD

**Issue by jmacweb** [thepirat000/Audit.NET#209]
How can we modify the EventType value before the Save() happens to make it more meaningful?  Referencing when I save data it uses the Context:Server or DB name?  Ours is the same for both, so not sure which is being pulled into the table.

Default: MyContext:HPTEST1 - I would like to modify this to Action:Entity so it is easier to search/filter by that field.  Something like

 Updated: [Table/Entity name]

I was able to add my own custom log event with custom names, but not for when DB SaveChanges() is called.

This works for a custom log event- 
 AuditScope.CreateAndSave("JSON View", new { JsonView = "TugRulesXref json", UserID = User.FindFirst(ClaimTypes.NameIdentifier).Value, UserName = User.FindFirst(ClaimTypes.Name).Value, UserEmail = User.FindFirst(ClaimTypes.Name).Value, UserRoleName = User.FindFirst(ClaimTypes.Role).Value, UserIpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString() });

Also, is there a way to get the OLD values without naming every field and doing the existing lookup first?  
I originally had 2 lines of code to perform the Save, and no worries for when the model changes, but now they are "hardcoded" so it is more tedious.

 //_context.TugRulesXref.Update(tugRulesXref);
                //_context.SaveChanges();
This results in the OLD and NEW values being the same.  I was able to get it working but there are a lot of tables and columns in this project.

Thanks for your help, this is very nice for auditing...additional SQL Views would help to find and view ONLY the changed values, since we don't need to see every value from the table in our history, only the modified columns.

Thanks, Justin
![image](https://user-images.githubusercontent.com/9578882/53994358-c0f6a480-40f7-11e9-8e18-6ee83280abad.png)

**Comment by thepirat000** [comment]
By default, the Audit EventType for EntityFramework events is `{context}:{database}`
{database} is the name of the database as seen by EF, actually for EF Core it is `dbContext.Database.GetDbConnection().Database`

It doesn't make too much sense to change it to {table}:{entity} because one EF event could potentially have multiple entries for multiple tables and actions, so it **only** makes sense if you assume every `SaveChanges()` in your code will affect only one entity. If that's the case, you can just have a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) to do that:

```
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    if (efEvent != null)
    {
        // this is an EF event, set the eventtype before saving assuming only one Entry
        var ent = efEvent.Entries.First();
        scope.Event.EventType = ent.Table + ":" + ent.EntityType.Name;
    }
});

```

About the update operation, that was already asked before and it has to do with the way EF sees the changes, nothing can be done on the library to avoid that, you must change your update code to retrieve the old values before updating. Check this issue https://github.com/thepirat000/Audit.NET/issues/53

**Comment by jmacweb** [comment]
Thank you for the fast reply.  This is helpful, and I was able to change the Updates to include the initial lookup by ID.  

I am seeing another Issue with the Username field...where is this pulling from?  In our DB we are seeing values for my user jmorris, and then the other two people testing are seeing Site1.  We are using WSFederation with local Active Directory, and jmorris matches my user/email, but the other users names should appear, not Site1.  I need to see WHO made the change, not a service account or IIS App Pool Account (not sure why it would be different there).

![image](https://user-images.githubusercontent.com/9578882/54149580-7c734d80-4404-11e9-96bf-4efcaf51c573.png)

**Comment by jmacweb** [comment]
This is just FYI, I received an error on your code above, it should read - using ent.Action, now that I was able to update the View with additional columns, you are correct this is not needed, but I do think I want to add the custom fields i have for the real site username, ip, :

{"EventType":"Page View","Environment":{"UserName":"jmorris","MachineName":"HPTEST1","DomainName":"HOUSTON-PILOTS","CallingMethodName":"WebAppPLS.Controllers.BillingController+<Index>d__5.MoveNext()","AssemblyName":"WebAppPLS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Culture":"en-US"},"StartDate":"2019-03-11T18:35:05.994514Z","EndDate":"2019-03-11T18:35:06.0062161Z","Duration":12,"PageView":"Billing","**UserID**":"8fb69161-b647-4c48-a142-da3f0a9cdb03","**UserName**":"jmorris@houston-pilots.com","**UserEmail**":"jmorris@houston-pilots.com","**UserRoleName**":"Super_Admin","**UserIpAddress**":"::1"}

I am using this in the Controller, but it doesn't work in Startup...any help to add these values in Startup?

 AuditScope.CreateAndSave("Page View", new { PageView = "Billing", UserID = User.FindFirst(ClaimTypes.NameIdentifier).Value, UserName = User.FindFirst(ClaimTypes.Name).Value, UserEmail = User.FindFirst(ClaimTypes.Name).Value, UserRoleName = User.FindFirst(ClaimTypes.Role).Value, UserIpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString() });

Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    if (efEvent != null)
    {
        // this is an EF event, set the eventtype before saving assuming only one Entry
        var ent = efEvent.Entries.First();
        scope.Event.EventType = ent.Table + ":" + **ent.Action;**
    }
});

![image](https://user-images.githubusercontent.com/9578882/54150512-a6c60a80-4406-11e9-83d1-cac54f2b1a55.png)

**Comment by jmacweb** [comment]
One last comment, is that because we are now adding the Select first, it shows all the columns as Changed even though we may have only changed 1 or 2 values.  How do we only show the Columns that actually changed?

Below only ShipType, IsThrusterSubstituteAllowed, IsWideBody were modified...

I added the code to another update where I specify only the two columns because nothing else matters, and that shows only those two columns.  In the scenario below, I do not know what the user might change...

"Valid": true,
        "Changes": [
          {
            "ColumnName": "BeamMax",
            "OriginalValue": 1001,
            "NewValue": 1001
          },
          {
            "ColumnName": "BeamMin",
            "OriginalValue": 10,
            "NewValue": 10
          },
          {
            "ColumnName": "DockName",
            "OriginalValue": "AG1",
            "NewValue": "AG1"
          },
          {
            "ColumnName": "DraftMax",
            "OriginalValue": 110,
            "NewValue": 110
          },
          {
            "ColumnName": "DraftMin",
            "OriginalValue": 1,
            "NewValue": 1
          },
          {
            "ColumnName": "HeadingDirection",
            "OriginalValue": "S",
            "NewValue": "S"
          },
          {
            "ColumnName": "IsActive",
            "OriginalValue": true,
            "NewValue": true
          },
          {
            "ColumnName": "IsThrusterSubstituteAllowed",
            "OriginalValue": false,
            "NewValue": true
          },
          {
            "ColumnName": "IsWideBody",
            "OriginalValue": false,
            "NewValue": true
          },
          {
            "ColumnName": "LoaMax",
            "OriginalValue": 10,
            "NewValue": 10
          },
          {
            "ColumnName": "LoaMin",
            "OriginalValue": 10,
            "NewValue": 10
          },
          {
            "ColumnName": "Notes",
            "OriginalValue": "This is a test record!",
            "NewValue": "This is a test record!"
          },
          {
            "ColumnName": "ShipType",
            "OriginalValue": "BRG",
            "NewValue": "BLK"
          },
          {
            "ColumnName": "TugCountMax"
          },
          {
            "ColumnName": "TugCountMin"
          },
          {
            "ColumnName": "TugRulesId",
            "OriginalValue": 1,
            "NewValue": 1
          },
          {
            "ColumnName": "TugSizeMax"
          },
          {
            "ColumnName": "TugSizeMin"
          }
        ]
      }
    ],
    "Result": 1,
    "Success": true

**Comment by thepirat000** [comment]
You're right, you shouldn't use the `ent.EntityType.Name`, instead you can get the entity type name with `ent.GetEntry().Entity.GetType().Name`

About the error, there are some things I don't understand...

What's the purpose of your `CreateAndSave` call? do you want to enrich the EF events with some external info like the ActiveDirectory user? if that's the case, you are doing it wrong because that's not the purpose of `CreateAndSave`. The CreateAndSave will just create an additional and isolated audit log entry including the anonymous object your are passing to it.

If you want to enhance/enrich the audit logs created by the library, you should use custom actions / custom fields. I guess you should be able to get the `User` object on your startup logic, if you're using ASP.net you can probably use the [`HttpContextAccessor`](https://stackoverflow.com/a/52135130/122195) like:

```c#
public class Startup
{
    // ...

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        var svcProvider = services.BuildServiceProvider();

        Audit.Core.Configuration.AddOnSavingAction(scope =>
        {
            var ctx = svcProvider.GetService<IHttpContextAccessor>();
            var userId = ctx.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userName = ctx.HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            scope.SetCustomField("User", new { userId, userName });
        });
    }
}
```


For your last question, can you share the logic for the update?

**Comment by jmacweb** [comment]
The above code worked perfectly.  Thank you.

Here is the code to update and produce the json above...

`[Authorize]
        [HttpPost]
        public async Task<ActionResult> TugRulesXref_UpdateAsync([DataSourceRequest] DataSourceRequest request, Models.TugRulesXref tugRulesXref)
        {
            if (tugRulesXref != null && ModelState.IsValid)
            {
                var _PrevTugRulesXref = await _context.TugRulesXref.FindAsync(tugRulesXref.TugRulesXrefGuid);
                _PrevTugRulesXref.BeamMax = tugRulesXref.BeamMax;
                _PrevTugRulesXref.BeamMin = tugRulesXref.BeamMin;
                _PrevTugRulesXref.DockName = tugRulesXref.DockName;
                _PrevTugRulesXref.DraftMax = tugRulesXref.DraftMax;
                _PrevTugRulesXref.DraftMin = tugRulesXref.DraftMin;
                _PrevTugRulesXref.HeadingDirection = tugRulesXref.HeadingDirection;
                _PrevTugRulesXref.IsActive = tugRulesXref.IsActive;
                _PrevTugRulesXref.IsThrusterSubstituteAllowed = tugRulesXref.IsThrusterSubstituteAllowed;
                _PrevTugRulesXref.IsWideBody = tugRulesXref.IsWideBody;
                _PrevTugRulesXref.LoaMax = tugRulesXref.LoaMax;
                _PrevTugRulesXref.LoaMin = tugRulesXref.LoaMin;
                _PrevTugRulesXref.Notes = tugRulesXref.Notes;
                _PrevTugRulesXref.ShipType = tugRulesXref.ShipType;
                _PrevTugRulesXref.TugCountMax = tugRulesXref.TugCountMax;
                _PrevTugRulesXref.TugCountMin = tugRulesXref.TugCountMin;
                _PrevTugRulesXref.TugRulesId = tugRulesXref.TugRulesId;
                _PrevTugRulesXref.TugSizeMax = tugRulesXref.TugSizeMax;
                _PrevTugRulesXref.TugSizeMin = tugRulesXref.TugSizeMin;

                _context.Entry(_PrevTugRulesXref).State = EntityState.Modified;
                _context.SaveChanges();


                //All I needed before Audit.NET to save
                 //_context.TugRulesXref.Update(tugRulesXref);
                //_context.SaveChanges();

               
            }

                return Json(new[] { tugRulesXref }.ToDataSourceResult(request, ModelState));
        }`

**Comment by jmacweb** [comment]
What would be the best way to capture in the same Event table, the page views and the json views.  That is where the Custom CreateandSave code above was being used.  I would like to use the Action field to insert Page View or Json View, so I can filter on that column for reporting for all Events?

![image](https://user-images.githubusercontent.com/9578882/54155716-c3683f80-4412-11e9-8fa4-a0113bd4b0ad.png)

**Comment by thepirat000** [comment]
I don't know what do you mean by "page view" or "json view", I guess they are values you have on the MVC controller, but not on the data layer.

If this an ASP.NET app, you could use one of the extensions that helps to audit ASP.NET: [Audit.MVC](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.Mvc/README.md) and [Audit.WebApi](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.WebApi).

**Comment by jmacweb** [comment]
Yes, just a simple User visitied page or view json response tracker.

Are you suggested to use all 3 and they all use the samve Event Table and View in the same database?

**Comment by thepirat000** [comment]
You don't need this line: `_context.Entry(_PrevTugRulesXref).State = EntityState.Modified;` actually that's causing the changes collection to include all the columns regardless of its previous value.

If you used this `_context.TugRulesXref.Update(tugRulesXref);`, then the `UPDATE` operation sent to the Database will **always** include all the columns on its SET statement regardless if they changed or not. So that is sub-optimal also.

What I suggest is to:

1. Keep using Audit.EF for the EF events. But use `Audit.MVC`, `Audit.WebApi` and/or _manual events_ for the extra event sources.

2. In order to be able to group the different events from the different sources, you should include a Correlation ID. In ASP.NET Core you can use the [Trace Identifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.traceidentifier?view=aspnetcore-2.2) that is unique per user request:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	var httpContext = ctxAccesor.HttpContext;
	scope.Event.CustomFields[CorrelationIdField] = httpContext.TraceIdentifier;
});
```

3. Since the Entity Framework Data Provider is unable to handle events that are not generated by EF itself (i.e. the EF data provider is unable to process the MVC events), you will need to use a different data provider for all the events, or at least for the non-EF events (for example check [this](https://github.com/thepirat000/Audit.NET/issues/210#issuecomment-471358639).

**Comment by jmacweb** [comment]
The CorrelationId worked perfect, and I added all 3 of the nugets using .NET Core and they all flow into the same SQL 2016 DB I set up with your scripts, then modified a SP to output back to a View in the using Telerik .NET Core Grid.  Very Very nice.  

After removing that line the Changes field only shows the modified columns.  Thank you very much, this is going to work great.

I was referring to slicing the data to create view for Auditing updates to the tables (i need to show a log on each Entity Page with history), and another view for Page View data, or other custom events, such as sending emails from the system.  Once I finish with the SP it will be able to power the Grids and Details pages.

Very nice!
