### ISSUE TITLE
EXM~I have some questions in custom dataprovider

### ISSUE THREAD

**Issue by i542873057** [thepirat000/Audit.NET#241]
In dataprovider,what time "InsertEventAsync " function will be trigged.If i code like this. 
e.g：
```
public override object InsertEvent(AuditEvent auditEvent)
        {
            KafkaHelper.Instance().Produce(this._kafkaConfigService.Configurations.BrokerList, "auditlog",
                "nci-bids-log", JsonHelper.ToJson(auditEvent));

            return Guid.NewGuid();
        }

        public override Task<object> InsertEventAsync(AuditEvent auditEvent)
        {
            KafkaHelper.Instance().Produce(this._kafkaConfigService.Configurations.BrokerList, "auditlog",
                "nci-bids-log", JsonHelper.ToJson(auditEvent));
            return base.InsertEventAsync(auditEvent);
        }
```
Will the same record send to kafka?

**Comment by thepirat000** [comment]
I'm assuming you're inheriting from `AuditDataProvider`.

The implementation of [`AuditDataProvider.InsertEventAsync`](https://github.com/thepirat000/Audit.NET/blob/d4dc9cdb0e429e6ed4ee623f8420c336d0dae717/src/Audit.NET/AuditDataProvider.cs#L58) calls the sync `InsertEvent` and return a completed task.


    public abstract class AuditDataProvider
    {
        ...
        public virtual async Task<object> InsertEventAsync(AuditEvent auditEvent)
        {
            // Default implementation calls the sync operation
            return await Task.Factory.StartNew(() => InsertEvent(auditEvent));
        }
        ...
    }

So, if your implementation of `InsertEventAsync` contains the logic to insert the event, **you should not call `base.InsertEventAsync`**. But since the logic for your insert is the same (it's actually not async), you could just remove your `InsertEventAsync` implementation and let the base implementation call your sync `InsertEvent` method.
