### ISSUE TITLE
Audit.WebAPI EntityFramework data provider

### ISSUE THREAD

**Issue by sashiRachakonda** [thepirat000/Audit.NET#288]
can Audit.NET Entity Framework Data Provider be used to save Audit.NET WebAPI audit logs?
if so, please provide an example.

Thanks,
-Sashi

**Comment by thepirat000** [comment]
That's not possible since the EF data provider is designed to exclusively store EF audit events.

You could probably use the [SqlServer Data Provider](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.SqlServer/README.md) or with a [custom data provider](https://github.com/thepirat000/Audit.NET#data-providers).

**Comment by sashiRachakonda** [comment]
thanks for the clarification.
