### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by trikk86** [thepirat000/Audit.NET#310]
Audit,EntityFramework,Core  15,2.3
Audt.NET 15.2.3

Project is in netstandard 2.0
Why does it reference EF 2.2.4?

I use Microsoft.EntityFramework.Core 3.1.6 (I need it due to other dependencies)

am I missing something?

_Originally posted by @trikk86 in https://github.com/thepirat000/Audit.NET/issues/231#issuecomment-661867342_

**Comment by thepirat000** [comment]
Looks like MS changed the target framework between the 3.* versions of `Microsoft.EntityFrameworkCore` package.

- `Microsoft.EntityFrameworkCore` 3.0.x target the .NETSTANDARD 2.1
- `Microsoft.EntityFrameworkCore` 3.1.x now targets the .NETSTANDARD 2.0

That's why the `Audit.EF.Core` was referencing the `Microsoft.EntityFrameworkCore` 2.2.4 for .NETSTANDARD 2.0, because of the lack of support before `Microsoft.EntityFrameworkCore` 3.1

So now I will change the `Audit.EF.Core` to target 3.* versions starting on .NETSTANDARD 2.0

This is the package reference relation right now:

![image](https://user-images.githubusercontent.com/9836380/88213586-89ba6200-cc1e-11ea-8678-35d0dcd610b4.png)

And I'll change it to:

![image](https://user-images.githubusercontent.com/9836380/88213718-b9696a00-cc1e-11ea-9048-cf8dc585dfcc.png)

**Comment by jalbrzym** [comment]
@thepirat000 Can you tell me when (approximately) this change will be applied and published?

**Comment by thepirat000** [comment]
maybe today if I have some time to work on it. 
Still having some package compatibility issues that need to be fixed for `Audit.EF.Identity` projects..

Specially because the library `Microsoft.AspNetCore.Identity.EntityFrameworkCore` doesn't have a version that supports .NET Standard 2.0 and references EF.Core 3.1, so I'll probably have to remove support for .NET Standard 2.0, and upgrade to .NET Standard 2.1 (hopefully this will be only for `Audit.EntityFramework.Identity.*` libraries.

**Comment by thepirat000** [comment]
This was fixed on version 15.3.0, please upgrade your references and re-test

**Comment by jalbrzym** [comment]
@thepirat000 Have you considered upgrading Entity Framework Core version for **net461** target as well?
![image](https://user-images.githubusercontent.com/4894611/88386963-cbc7dd00-cdb1-11ea-8b19-d46c2657e2c6.png)
