### ISSUE TITLE
Replace at the end instead of Insert

### ISSUE THREAD

**Issue by romazhab** [thepirat000/Audit.NET#325]
**Describe the bug**
After executed API action method audit event replaced insted of insert called. EventCreationPolicy doesn't matter (InsertOnStartInsertOnEnd or InsertOnStartReplaceOnEnd same behavior)

**To Reproduce**
1. Setup configuration with the `EventCreationPolicy.InsertOnStartInsertOnEnd`
2. Use `[AuditApi]` attribute in your controller.
3. Execute API action
In debug mode you can see that at the end of the API action the method `AuditApiAdapter.AfterExecutedAsync()` called. Then `auditScope.SaveEventAsync()` without any arguments and does not take сreation policy into account.

**Expected behavior**
Audit event should be inserted instead of replaced.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.WebApi.Core: 16.0.3
 - Audit.NET: 16.0.3

**Target .NET framework:**
 - .NET Core 3.1

**Comment by romazhab** [comment]
`                // Replace the Action field 
                (auditScope.Event as AuditEventWebApi).Action = auditAction;
                // Save, if action was not created by middleware
                if (!auditAction.IsMiddleware)
                {
                    await auditScope.SaveAsync();
                }`

**Comment by thepirat000** [comment]
you're completly right

I think I'll change it to call `DisposeAsync()` instead of `SaveAsync()`

The only problem I see is that it will break compatibility when using "Manual" policy, since `DisposeAync()` will not trigger the event saving. But that makes senses; when using a Manual policy it is supposed that you have to call AuditScope's Save by your own.

Will run the tests and let you know

**Comment by thepirat000** [comment]
This was fixed on version 16.1.0, please upgrade your references and re-test
