### ISSUE TITLE
Exception occurred when input data has html code

### ISSUE THREAD

**Issue by tommywulove** [thepirat000/Audit.NET#34]
Hi @thepirat000 
I got an error when the request form data has html code, the Audit.Mvc.AuditAttribute class method private static IDictionary<string, string> ToDictionary(NameValueCollection col) occur an exception "System.Web.HttpRequestValidationException: 'A potentially dangerous Request.Form value was detected from the client (Html="<a></a><br>").'" , would you help to check this issue? 
Below image for your reference.

![image](https://cloud.githubusercontent.com/assets/2859394/23837327/6001321a-07c1-11e7-864c-4d0d83998af6.png)

**Comment by thepirat000** [comment]
This is not related to Audit.NET, that's an ASP.NET exception that will be thrown by default whenever you try to access a form value that contains unencoded HTML.
Since you are passing unencoded HTML, when the Audit.NET library tries to access the form value, the exception is thrown.

You can explicitly avoid the exception. For example, take a look at http://stackoverflow.com/questions/81991/a-potentially-dangerous-request-form-value-was-detected-from-the-client

**Comment by tommywulove** [comment]
Here is the code of controller. added the ValidateInput(false) attribute, but still throw exception .

![image](https://cloud.githubusercontent.com/assets/2859394/23837740/0a6628fe-07c8-11e7-9fa8-eb515269b4b2.png)

**Comment by thepirat000** [comment]
oh ok, let me try to reproduce it here

**Comment by thepirat000** [comment]
You were right, sorry.

I've made a change on the library so the validations will not be triggered by the Audit form values retrieval.

Please upgrade to latest version (>= 7.0.2) and let me know if you still have problems.

Regards
