### ISSUE TITLE
Add System.Text.Json Support

### ISSUE THREAD

**Issue by salarzobir** [thepirat000/Audit.NET#356]
When targeting .NET Core 3.0 or higher using System.Text.Json will increase the performance and reduce the memory usage.
Maybe the json serializer could be like a provider that user can change it when configure Audit.NET

**Comment by thepirat000** [comment]
That would be nice to have, but will be a very hard task since the library is highly coupled with newtonsoft.json, specifically with the use of the attributes `JsonExtensionData` and `JsonProperty` to annotate all the audit event classes on most of the extensions.

So we'll need to first circunvent all the compile-time issues like this in order to provide a way to select the serialization mechanism at run-time.

Feel free to make any suggestions for this

**Comment by thepirat000** [comment]
I still think providing a mechanism to change the serialization at run-time will be very hard to accomplish.

Maybe we can just use system.text.json internally intead of json.net on the assemblies targeting >= .net core 3, and if it was needed, provide alternative assemblies/packages to force the non-default serializarion mechanism

**Comment by thepirat000** [comment]
I've started trying with System.Text.Json and in less than 5 minutes I've found two open issues that will prevent a smooth migration:

- Missing reference loop handling setting:  https://github.com/dotnet/runtime/issues/40099
- Missing serialization from DOM: https://github.com/dotnet/runtime/issues/31274

So I think that, at this time, `System.Text.Json` api is not mature enough to start the migration of this library.

**Comment by thepirat000** [comment]
835898311b7c5831b4c7b1ef7497c55189dafc8a

**Comment by thepirat000** [comment]
Added support to `System.Text.Json` starting on version 18 (only for .NET >= 5.0)

Refer to the following README sections:

- [Breaking change on version 18](https://github.com/thepirat000/Audit.NET/blob/master/README.md#breaking-change-in-version-18)
- [Global serialization mechanism](https://github.com/thepirat000/Audit.NET/blob/master/README.md#global-serialization-settings)

All the libraries were impacted since this was a very big change (184 files changed) so please expect some backward compatibility issues on the new serializarion mechanism, specially since the `System.Text.Json` doesn't support (yet?) a lot of things that Newtonsoft.Json does.

Please upgrade your references to version 18.0.0 and test.
