### ISSUE TITLE
Ignore related items

### ISSUE THREAD

**Issue by avialonn** [thepirat000/Audit.NET#364]
Hi there,
Is it possible to skip related entities on saving?

I have the following object:

person.Addresses

I also do some changes to the addresses list but on save I will only need to audit the person object rather than his addresses.

Im on .net 5 with EF provider.

Will appreciate any input on this one.
Thanks!
AA

**Comment by thepirat000** [comment]
Did you tried with `[AuditIgnore]` attribute on the Addresses property?

https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#exclude-properties-columns

**Comment by avialonn** [comment]
Thanks for the quick reply!
Yes, I did but with no success.
It's a navigation property.

**Comment by thepirat000** [comment]
In that case, you'll need to add your custom logic to skip the audit entries you don't want to save. 

Please share your configuration code, but if you're using the EF data provider, you could decide on the `AuditEntityAction` function. If you make this function return false, the entity will not be included on the output. Check [this example](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#ignore-certain-entities-on-the-audit-log)

Another option is to use a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) to override the audit event. Check [this example](https://github.com/thepirat000/Audit.NET/issues/359#issuecomment-768469922)

**Comment by avialonn** [comment]
The last example seems the best fit! 
However, is it possible to get the CustomField there. for some reason, it is not included and I get 0 in the array.
I do get it in the OnEventSaving customfilter but it is too late.
Thanks

**Comment by thepirat000** [comment]
What custom field? you should share the code

**Comment by avialonn** [comment]
On each save im adding an action:

public async Task<int> SaveChangesAsync(TimelineActionEnums action)
        {
            base.AddAuditCustomField("TimelineAction", (int)action);
            return await base.SaveChangesAsync();
        }

**Comment by thepirat000** [comment]
You should be able to get them from the audit event like `efEvent.CustomFields["TimelineAction"]`

**Comment by avialonn** [comment]
I did, but also there I don't see the custom field.

**Comment by avialonn** [comment]
I see that I missed the fact that these custom fields are global.
Is there something I can do per execution?

**Comment by thepirat000** [comment]
I don't know what you mean by global, but they are local to a scope (each audit event have their own custom fields). 
In your case, since you are using the `AddAuditCustomField()` method on the AuditDbContext, those custom fields will be included on all the audits triggered by SaveChanges for that particular DbContext instance. Do you re-use the same DbContext instance?

Anyway I saw a bug that I'll fix: the custom fields that are set via `AuditDbContext.AddAuditCustomField()`, are actually added to the audit event right AFTER the scope creation. That's why you don't see them on the OnScopeCreated event. I will change this so the custom fields are there when the event is triggered

Scope creation: https://github.com/thepirat000/Audit.NET/blob/04fecbbc691459d01b2a2115dfaabe8d22ae4115/src/Audit.EntityFramework/DbContextHelper.cs#L361
Custom fields: https://github.com/thepirat000/Audit.NET/blob/04fecbbc691459d01b2a2115dfaabe8d22ae4115/src/Audit.EntityFramework/DbContextHelper.cs#L364

**Comment by avialonn** [comment]
Yes, I do reuse the context. That explains it. 
Thanks for the bug fixing!
For now, I just pass the relevant data via NotMapped prop. But will surely test it when the fix is up!

**Comment by thepirat000** [comment]
This was fixed on version 16.4.4, please upgrade your references and re-test.

**Comment by avialonn** [comment]
Awesome!
