### ISSUE TITLE
Audit.WebApi.Core AuditIgnoreAttribute for property in class or entire class

### ISSUE THREAD

**Issue by salarzobir** [thepirat000/Audit.NET#380]
How to ignore auditing request/response model by adding attribute on top of class to ignore all class usages in all actions, or one or more property to be ignored in all class usages in all actions.

```
public class SomeClass1
{
    [AuditIgnore]
    public string Code { get; set; }

    public string Name { get; set; }
}
```

```
[AuditIgnore]
public class SomeClass2
{
    public string Code { get; set; }

    public string Name { get; set; }
}
```

I want this to take effect in all actions uses this classes.
**Note:** I don't want to use `JsonIgnore` because it should be still serializable.

**Comment by thepirat000** [comment]
There is no generic automagic way to do that. Are those object classes being used as parameters, return values, input value or where on the audit event are they stored?

**Comment by salarzobir** [comment]
I am using this as action method parameter, some of this classes used as return values

**Comment by thepirat000** [comment]
Which data provider are you using?

The `AuditIgnoreAttribute` defined on `Audit.WebApi` is intended to be used on the controller and/or action method directly, not on the model classes. I guess you already know that but you want to ignore some specific model properties.

I think the only way to accomplish this will be to handle the audit output before saving to manually detect and override the properties that needs to be ignored. This could be done on a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) or with a custom [Data Provider](https://github.com/thepirat000/Audit.NET#data-providers)

```c#
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var audit = scope.GetWebApiAuditAction();
                
    var requestBody = audit.RequestBody?.Value; // <-- the request body as a JSON string
    var requestParams = audit.ActionParameters; // <-- the action parameter objects
    var responseBody = audit.ResponseBody?.Value; // <-- the response body object (if the action returns an ObjectResult)
});
```

If you want something generic, you will probably need to recursively reflect the properties and handle cases like reference loops.

Also note the Request Body cannot be read as an object on the audit event since it's read directly from the buffer stream as a string.
