### ISSUE TITLE
Complex properties not tracked

### ISSUE THREAD

**Issue by passion2** [thepirat000/Audit.NET#42]
Hello,

I'm not sure if missed anything in the docs.
I'm trying to track EF 6 entity changes.
For simple properties it works, but for complex properties (foreign key) the change is simply ignored.

Any suggestion?

Thanks,
Sandor

**Comment by thepirat000** [comment]
Can you share more details? like the code where you are making the changes?

**Comment by passion2** [comment]
Please see the code below, I hope it's clear enough:

`namespace AuditDemo
{
    public class MyContext :  AuditDbContext
    {
        public DbSet<MainClass> Mains { get; set; }
        public DbSet<OtherClass> Others { get; set; }
    }

    public class MainClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public OtherClass OtherClass { get; set; }
    }

    public class OtherClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            var myContext = new MyContext();

            var other1 = new OtherClass { Name = "Other 1" };
            var other2 = new OtherClass { Name = "Other 2" };
            myContext.Others.Add(other1);
            myContext.Others.Add(other2);
            myContext.SaveChanges(); // Tracking ok (insert)

            var main = new MainClass { Name = "Name 1", OtherClass = other1 };

            myContext.Mains.Add(main);
            myContext.SaveChanges(); // Tracking ok (insert)

            var myContext2 = new MyContext();

            var editMain = myContext2.Mains.FirstOrDefault();

            editMain.Name = "Modified Name 1";
            myContext2.SaveChanges(); // Tracking ok (update)

            editMain.OtherClass = myContext2.Others.FirstOrDefault(f=> f.Name == "Other 2");
            myContext2.SaveChanges(); // Tracking failed (update)
        }       
    }
}
`

**Comment by passion2** [comment]
So, no solution for this problem?

**Comment by thepirat000** [comment]
Audit.EntityFramework uses the EF's `DbContext`. The DbContext is unable to track Relationship State, it only tracks Entity State, and your `MainClass.OtherClass` is a relationship. 

Take a look at [this SO question](http://stackoverflow.com/questions/11670212/entity-framework-wont-detect-changes-of-navigation-properties/11670457).

I think the easiest way to solve it is to update the foreign key ID instead of the object reference:

```c#
editMain.OtherClassId = myContext.Others.FirstOrDefault(f => f.Name == "Other 2").Id;
```

Another way could be to use the `ObjectStateManager` from the library, but that will take some time, and I'm unable to work on this for the following few weeks.

Hope it helps
