### ISSUE TITLE
Error on SaveChanges() using EntityFramework Table per Type

### ISSUE THREAD

**Issue by rkaminski96** [thepirat000/Audit.NET#421]
**Describe the bug**
As it seems, framework incorrectly works with EntityFramework Table per Type approach. The issue happens when trying to create and save an instance of derived class, I get an error "Value cannot be null. (Parameter 'key')". After switching from AuditDbContext to DbContext it works fine. 

**To Reproduce**
https://github.com/rkaminski96/Audit 
Please run a sample project and make request from Swagger.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET: 17.0.4
 - Audit.EntityFramework: 17.0.4

**Target .NET framework:**
 - .NET 5.0
 - EntityFrameworkCore 5.0.7

**Comment by thepirat000** [comment]
Supporting Table per Type will introduce some complexity and will probably break the current EF audit output format. 

TPT implies that a single _entry_ on the _entity tracker_ could map to more than one table (in your example, adding a new `ReservationRequest` implies inserts to two tables _ReservationRequests_ and _Requests_) 

So the current audit output format will not fit, since it assumes each [EventEntry](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#evententry) corresponds to a single table and to a collection of columns on that table.

Please expect some delay in fixing this since it will need more analysis

**Comment by rkaminski96** [comment]
Thank you for the quick reply. Now I understand problems caused by TPT approach in relation to your framework. 
How do you think, is there any solution other than not using TPT at this point?  Does it look like I have to wait for a possible extension of the framework's capabilities into the future?

**Comment by rkaminski96** [comment]
Thank you for quick answear.

**Comment by thepirat000** [comment]
I think I could provide an intermediate fixed version with the known issue that the TableName reported on the audit for those entries will be always the Parent table, and the column changes will include the columns of both tables.

**Comment by rkaminski96** [comment]
I think it is worth to test this solution. Thanks in advance.

**Comment by thepirat000** [comment]
Fixed on 5b317361def70a4af23002778346ceb995e08155

Please upgrade your references to the latest version (17.0.8) and re-test
