### ISSUE TITLE
Feature Request: Configure Azure Blob Tier

### ISSUE THREAD

**Issue by adnang** [thepirat000/Audit.NET#429]
It would be really useful if we could configure the [standard blob tier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob.setstandardblobtierasync?view=azure-dotnet-legacy) used when creating the event blobs

Something like a `IAzureBlobProviderConfigurator.WithBlobTier(Func<AuditEvent,StandardBlobTier>)` method to call within `UseAzureBlobStorage()`

Our use case is to use the `Cool` pricing tier rather than the default `Hot`. We've worked around it for now using a storage management policy which changes the tier after some amount of time since uploading, but it would be better to set the `Cool` tier at the source when we upload

**Comment by thepirat000** [comment]
In order to enable that configuration, we'll need to upgrade to the latest Azure nuget package (`Azure.Storage.Blobs`) that allows changing the standard blob tier, but since `Audit.AzureStorage` library is currently handling Tables and Blobs, and the Microsoft library has been splitted, it will also probably require the `Audit.AzureStorage` library to be split.

Also these new libraries only supports >= netstandard2.0:

- https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
- https://www.nuget.org/packages/Azure.Storage.Blobs

So I guess the best we can do is to create two new libraries `Audit.NET.AzureBlob` / `Audit.NET.AzureTable` that will be compatible with netstandard2.0 or higher, and will provide a way to configure the tier and/or the entire Blob Client.

But of course that will require some time.

**Comment by thepirat000** [comment]
oh, I just realized that actually **there is** a way to set the standard blob tier on the legacy version 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob.setstandardblobtier?view=azure-dotnet-legacy

So I think I can provide the configuration as you requested still using `WindowsAzure.Storage`

Anyway in a future a split will be needed for this library to use the latest client

**Comment by thepirat000** [comment]
Support to change the [Access Tier](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers) was added on version 18.1.0, please upgrade your references and re-test.

You can now change the access tier using [`WithAccessTier()`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.AzureStorage/README.md#container-options) fluent API, for example:

```c#
Audit.Core.Configuration.Setup()
	.UseAzureBlobStorage(config => config
		.ConnectionString(...)
		.ContainerName(...)
		.BlobName(...)
		.WithAccessTier(StandardBlobTier.Cool));
```

Please note that using this setting implies that each upload will require two calls: one to upload the blob, and another one to set the access tier, since I couldn't find a way to specify the access tier on the upload operation with the legacy library (`WindowsAzure.Storage`). 

Also a new setting was added `WithMetadata()` that allows to relate [user-defined metada](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata?tabs=dotnet) to the blobs.

**Comment by thepirat000** [comment]
A new data provider for Azure Storage Blob is provided: [Audit.NET.AzureStorageBlobs](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.AzureStorageBlobs/README.md)

This new package uses the latest client library version and will not require the two calls when changing the AccessTier, since the AccessTier is set when updating the blobs.

commit babb248197db12233be0c203b5582fa3a416f9ca 

Please upgrade to use this new library Audit.NET.AzureStorageBlobs

**Comment by adnang** [comment]
brilliant, thanks!
