### ISSUE TITLE
Dates serialized a strings

### ISSUE THREAD

**Issue by alejandrojrey** [thepirat000/Audit.NET#457]
Hi, i'm having the same issue described in https://github.com/thepirat000/Audit.NET/issues/173#issue-373923500.

The StartDate and EndDate properties are beeing saved as strings.

![image](https://user-images.githubusercontent.com/12596957/133637498-403a1330-3c3b-412d-859f-c1807b28d302.png)

This even happen with customs date properties.

Libraries:

Audit.Net: 18.1.5
Audit.Net.EntityFramework.Core 18.1.5
Audit.Net.MongoDb: 18.1.5

**Comment by thepirat000** [comment]
What's your target .net framework version?

**Comment by alejandrojrey** [comment]
I'ts Net Core 3.1

**Comment by thepirat000** [comment]
The problem is that JSON doesn't have a representation for Dates, and by default the Audit library serializes to JSON and then parses to BSON.

So I think the solution is to set `SerializeAsBson` to true on the MongoDB Data Provider configuration.

```c#
Audit.Core.Configuration.Setup()
    .UseMongoDB(c => c
        .ConnectionString("mongodb://localhost:27017")
        .Database("Audit")
        .Collection("Issue457")
        .SerializeAsBson(true))
    .WithCreationPolicy(EventCreationPolicy.InsertOnEnd);
```

That way the objects are directly serialized as BSON without having to pre-serialize to JSON. 
Please check this: https://jira.mongodb.org/browse/CSHARP-2233

**Comment by alejandrojrey** [comment]
Thank you, that did the trick, unfortunally that also change how te custom properties are saved :-(

I needed in order to filter events so i ended up adding a custom field with the date as number.

long.Parse(DateTime.Now.Date.ToString("yyyyMMdd"))

**Comment by thepirat000** [comment]
do you need the custom fields serialized differently?

**Comment by alejandrojrey** [comment]
The problem was that the custom fields were saved as an object with a _t and _v properties instead of being an int, string, etc.
I have already a bunch of process that use those fields so changing them is not an option.

But dont worry, i solved the issue saving the date as number.

**Comment by thepirat000** [comment]
yeah, never mind my previous message, I see what's the problem with the custom fields...

Note that there is a limitation on BSON documents: "_A DateTime value cannot be written to the root level of a BSON document_"

So, you the option to write the dates in a property instead of having the dates at the root level of the document, so they will be serialized properly, i.e.:

```c#
auditEvent.CustomFields["SomeDates"] = new { Date1 = DateTime.UtcNow, Date2 = DateTime.Now };
```c#

**Comment by thepirat000** [comment]
Also you can override the Serialize method on a custom data provider inheriting from MongoDataProvider, i.e.:

```c#
public class CustomMongoDbProvider : Audit.MongoDB.Providers.MongoDataProvider
{
    public CustomMongoDbProvider(Action<IMongoProviderConfigurator> config) : base(config) { }
    public override object Serialize<T>(T value)
    {
        if (value is DateTime dt)
            return new BsonDateTime(dt);
        return base.Serialize(value);
    }
}
```

So you can configure with:

```c#
Audit.Core.Configuration.Setup()
    .UseCustomProvider(new CustomMongoDbProvider(c => c
        .ConnectionString("mongodb://localhost:27017")
        .Database("Audit")
        .Collection("Issue457")
        .SerializeAsBson(true)));
```

So the DateTimes can be serialized properly as DateTime fields.
