### ISSUE TITLE
RavenDB storage provider

### ISSUE THREAD

**Issue by scattered-code** [thepirat000/Audit.NET#485]
Implemented a RavenDB storage provider supporting both full object storage and just diff of objects. Feel free to reference/ignore it, just making you aware of its existence. I will be maintaining it since I'm actively using it in a few projects

https://github.com/ops-ai/Audit.NET.RavenDB

Thanks for a great library!

**Comment by thepirat000** [comment]
Awesome!!!

**Comment by thepirat000** [comment]
I will use part of your code in order to provide a generic RavenDB data provider soon.

Thank you

**Comment by scattered-code** [comment]
Take a look at the custom serialization contract resolver when you do. Raven uses newtonsoft, and i had to create a way for the extension data attribute to be respected, since it's using the one from system.text.json in newer frameworks. 
I based much of the rest of the code on your elasticsearch implementation, but added a possibly more efficient way (still want to run some benchmarks) of deep cloning objects, and the diff.

**Comment by thepirat000** [comment]
I actually had to change a little bit the [contract resolver](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.JsonNewtonsoftAdapter/AuditContractResolver.cs) for compatibility with `System.Text.Json.Serialization.JsonIgnoreAttribute` (only when Condition=Always, at least for this initial version), and to support `IDictionary<>` and `Dictionary<>` types on the ExtensionData property.

@scattered-code I'm trying to push the new package Audit.NET.RavenDB, but since it already exists and you are the owner, I am unable to do so.

Could you add me as an owner of the package `Audit.NET.RavenDB` so I am able to push? Otherwise I'll need to change the package name (https://devblogs.microsoft.com/nuget/managing-package-owners/)

Thank you

**Comment by scattered-code** [comment]
Invitation sent

**Comment by thepirat000** [comment]
That was unbelievably fast!

The initial version of the [Raven DB data provider](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.RavenDB/README.md) was included on version 19.1.0

Please upgrade your references and re-test. 

Any comments are welcome.

Thank you again

**Comment by scattered-code** [comment]
@thepirat000 I like how you integrated the contract resolver! It might introduce a breaking change tho for existing data if anyone is using on a newtonsoft destination.
Any suggestions on how to go about storing only a diff instead of the full objects? In my case the objects are just too large to store 2 copies in each audit. I'm currently looking at a wrapper for RavenDbDataProvider, but would like something more generic.
Also, any plans to add a queryable interface into the events or some extension point where to add querying?

**Comment by thepirat000** [comment]
I think you could use a custom action in order to change the Target.Old and Target.New values before saving, so you probbaly don't need to wrap the data provider. for example:

```c#
Audit.Core.Configuration.Setup()
    .JsonNewtonsoftAdapter();

Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var auditEvent = scope.Event;
    if (auditEvent.Target != null)
    {
        var diff = ObjectDiffPatch.GenerateDiff(auditEvent.Target.Old, auditEvent.Target.New);
        auditEvent.Target.Old = diff.OldValues;
        auditEvent.Target.New = diff.NewValues;
    }
});
```

**Comment by thepirat000** [comment]
I have no plans for an IQueryable interface. 

So far, some of the data providers implement some querying mechanism, but they are not part of the common base data, just as extra methods on some data providers. The same could be done for RavenDbProvider.

Providing a unified querying mechanism is out of the scope of the Audit.NET library and I think it could be a pain since the diversity of the data providers. 

Anyway, all ideas are welcome, so if you see anything that could be useful I'm open to suggestions.

Thanks



I'm afraid will be could be
