### ISSUE TITLE
ID of navigation property incorrect at custom AuditDataProvider

### ISSUE THREAD

**Issue by Braidon** [thepirat000/Audit.NET#488]
**Describe the bug**
Navigation property id is incorrect at custom AuditDataProvider

**To Reproduce**
[EFTest.zip](https://github.com/thepirat000/Audit.NET/files/8570423/EFTest.zip)

**Expected behavior**
When add new child entity I expect to see ID = 1

**Libraries (specify the Audit.NET extensions being used including version):**
Audit.EntityFramework.Core 19.1.0
Audit.EntityFramework.Identity.Core 19.1.0

**Target .NET framework:**
.NET 6.0

**Additional context**
SQL Server required. Build, run, look at the History table.
![image](https://user-images.githubusercontent.com/10419475/165480051-31df6198-d5f6-487a-8ef0-b13d89053c1c.png)

**Comment by thepirat000** [comment]
The `Changes` property on the `EventEntry` is set **before** the actual SaveChanges takes place, so the Old and New values will refer to the values that were on the entity object before saving. That's why you see that value. 

On the other hand, the `ColumnValues` property **does** get updated **after** the actual SaveChanges takes place ([here](https://github.com/thepirat000/Audit.NET/blob/2ba7dfee1528ef4daf53e21db6796771cfedf582/src/Audit.EntityFramework/DbContextHelper.Core.cs#L275)), so I think I could add logic there to also update the values on the `Changes` property when the property is part of a foreign key

**Comment by thepirat000** [comment]
This was fixed on version 19.1.1, please upgrade your references and re-test.

The fix was to update any foreign key values on the Change property, after the savechanges

https://github.com/thepirat000/Audit.NET/blob/2d288b7030a089802cc9bfb8f1f8a9e1212e2f7f/src/Audit.EntityFramework/DbContextHelper.Core.cs#L297

**Comment by Braidon** [comment]
Everything works fine, thank you!
