### ISSUE TITLE
Pagination while fetching records

### ISSUE THREAD

**Issue by website-application** [thepirat000/Audit.NET#569]
Is there any option to fetch data in batches or with page size to avoid the complete data load for huge data.

**Comment by thepirat000** [comment]
In general, this library does not provide a mechanism to retrieve audit data, with the exception of some of the Data Providers that expose a basic GetEvent method.

So, it depends on where/how are you storing the audit events.

**Comment by granadacoder** [comment]
So I did some work on this... in post-gres land.

I do see the "tension point".  RDBMS (database) concrete stores..........there's a good chance you can work out some paging functionality.

Non RDBMS DataProviders (redis, etc)..... the idea of "look at all and get some" ... that is a different (and perhaps too impossible) to implement. (these non rdbms stores... is more about adding and then knowing the "key" to pull it out later)


@thepirat000  take a look at the PR:

https://github.com/thepirat000/Audit.NET/pull/572

I might be able to "mimic" for MySql and Ms-Sql-Server...but don't want to go down that path unless you see it has value....


I did the work because I do have a need to have paging functionality.      If this PR doesn't make the cut.. I'll have to implement a custom solution. :(  

So I am hoping this "makes the cut".

Thanks.



The other idea that popped into my head.... was .. I wonder if there might be a IRdbmsDataProvider "marking interface".. so the concrete dataproviders that are paging plausible can be separated from the ones that are paging plausible.

**Comment by thepirat000** [comment]
I've merged your pull request, just leaving out (for now) the EnumerateEvents with pagination parameters, as discussed in the PR. 

These changes are included in version 20.1.6

For reference, [here](https://github.com/thepirat000/Audit.NET/blob/1d8592afe115a7cb707fe576d093c6a5fe3b1703/test/Audit.IntegrationTest/PostgreSqlTests.cs#L118) is an example of how to expose a method to retrieve paginated records with the PostgreSql data provider:

https://github.com/thepirat000/Audit.NET/blob/1d8592afe115a7cb707fe576d093c6a5fe3b1703/test/Audit.IntegrationTest/PostgreSqlTests.cs#L118-L156
