### ISSUE TITLE
Audit.NET + WPF App

### ISSUE THREAD

**Issue by BogdanJak** [thepirat000/Audit.NET#580]
Hello

Is it possible to use the Audit.net library in a WPF application?
If possible, can you give me an example. I am interested in saving all changes in one table in MSSql database. I've read the tutorial but I don't really know where to put e.g. configuration in the WPF application.

**Comment by thepirat000** [comment]
There is no WPF extension and I'm affraid it will never be one, since there is no way to easily hook into all the events in a WPF application, unless some reflection/emit tricks are used, but even so it will really impact the performance of the application and not be really helpful. But maybe I'm missing something
