### ISSUE TITLE
Unwanted dependencies

### ISSUE THREAD

**Issue by shobhitvaish** [thepirat000/Audit.NET#59]
I found Audit.Mvc perfect for my needs but it seems to install lot of dependencies and some of them are from Asp.Net core. I wonder why I need them all? I am using .net framework 4.6.1

![image](https://user-images.githubusercontent.com/24998910/28856562-831b67ce-7761-11e7-9829-2b8224fd7f8a.png)

**Comment by thepirat000** [comment]
I think you're not referring to my packages.
Please note Audit.Mvc only has the following references, as you can see on the [nuget package](https://www.nuget.org/api/v2/package/Audit.Mvc/7.1.1):

![image](https://user-images.githubusercontent.com/9836380/28857326-53260360-770e-11e7-834c-b6e389a556de.png)

**Comment by shobhitvaish** [comment]
Yeah, that's right. I wonder why it try to install whole bunch of dependencies when some of them are already there?

**Comment by thepirat000** [comment]
Create a totally new project and import only Audit.Mvc and see if the same happens

**Comment by shobhitvaish** [comment]
No luck, same issue.

I even tried 4.5.2

![image](https://user-images.githubusercontent.com/24998910/28858333-7675e826-776d-11e7-872f-353c37d5f4e0.png)

**Comment by shobhitvaish** [comment]
Looks like the problem is with latest version of Audit.MVc. Version 7.1.0 works just fine.

**Comment by thepirat000** [comment]
The problem is that you are importing the library to an Asp.NET project, but starting from version 7.1.1, 
the library assumes that if you target framework >=4.5.1 you are using **Asp.NET Core** (Microsoft.AspNetCore.*), this change was because of [this issue](https://github.com/thepirat000/Audit.NET/issues/56).

Here the term Core is confusing... The Asp.NET Core product supports both the .NET core framework and the full framework... This will change on Asp.NET Core 2.0 since only the core framework will be supported.

As you can see on the nuget package, since you are targeting 4.5.2, the nuget install the 4.5.1 version that is ponting to Asp.NET Core

![image](https://user-images.githubusercontent.com/9836380/28876691-9f78bfe0-775f-11e7-8f58-d8d829c1d9d4.png)

You can try with the following trick, to have `Audit.Mvc` working on an Asp.Net (non core) project for framework >=4.5.1:
1. Create a new "ASP.NET Web Application (.NET Framework)" project **but** target the 4.5 framework

![image](https://user-images.githubusercontent.com/9836380/28876667-8c812ed6-775f-11e7-9145-ef57b7284e6f.png)

2. Install the Audit.Mvc package

3. Go to project properties and change the target framework to >= 4.5.1

4. Build your project
Your packages.config should now look like:
![image](https://user-images.githubusercontent.com/9836380/28876940-7b696e50-7760-11e7-8ff4-9c16882c47a1.png)

Just be aware that if you issue an update-package, the library will update to the 4.6.1 version.

**Comment by shobhitvaish** [comment]
Thanks for explanation! It works now

**Comment by shobhitvaish** [comment]
Hi again, Could you please let me know if there is a way to do not log passwords? It comes with form variables.

**Comment by thepirat000** [comment]
You could do that with [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions).

For example:

```
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var mvc = scope.Event.GetMvcAuditAction();
    if (mvc.FormVariables.ContainsKey("password"))
    {
        mvc.FormVariables["password"] = "******";
    }
});
```

The action passed to `AddCustomAction` will be executed for every event, before they are saved.

**Comment by shobhitvaish** [comment]
Thank you, that is awesome!
