### ISSUE TITLE
Question for WebApi: Audit only on statuscodes

### ISSUE THREAD

**Issue by esbenbach** [thepirat000/Audit.NET#620]
Hi
Is it possible, using the WebApi extension, to audit only if the response is of a given status code? There is already an `IncludeResponseBodyIf` option, and basically I would like a similar option for the entire Audit.

Either like an: `AuditIf` option or `IgnoreIfNot`.

I might be willing to spend some time on a PR contribution if it fits with the design goals.

**Comment by thepirat000** [comment]
You can accomplish what you want by setting up a custom action that discards the audit event:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    if (scope.GetWebApiAuditAction().ResponseStatusCode == 404)
    {
        scope.Discard();
    }
});
```

Anyway, you can work on a PR if you want, very welcome! 

Take into account that:
- There is no `IncludeResponseBodyIf`. Not sure if you are referring to the middleware's `IncludeResponseBody(Func<HttpContext, bool> includePredicate)` but that cannot filter on the response, since the predicate is executed before the action is called.
- The `AuditScope`/`AuditEvent` is created before the server processes the request, so if we provide a method to filter audits depending on the response, we should maybe call it `DiscardIf`, or something like that.
