### ISSUE TITLE
async await support

### ISSUE THREAD

**Issue by lineker** [thepirat000/Audit.NET#72]
any plans for this ?

**Comment by thepirat000** [comment]
not really...
I think async/await makes some sense only for the data providers, when saving the logs. 
That will imply changes in every data provider and it will probably break custom data providers on the clients, unless some default async is provided.

I will think more about it.

Do you have any specific problem with this lack of async/await?

**Comment by lineker** [comment]
for sure the benefit of async/await is when doing IO. I don't have a specific problem at the moment but I believe it would be a nice optimization. Default async is easy to achieve, unfortunately alot of libraries out there say that they are async/await but in reality they are faking.

**Comment by thepirat000** [comment]
I think the async pattern will only be useful for manual saving, (i.e. providing a `SaveAsync()` method on the `AuditScope`). But the library usually store the events at the moment of the scope creation and/or disposal, and those actions are not suitable for being async.

**Comment by thepirat000** [comment]
Reopening this since a refactor can be done to provide useful async methods on the `AuditScope` and the Data Providers.

Things that will need to be done:

- Implement internal `Start`/`StartAsync` methods on the audit scope to decouple the creation of the event from the constructor, since `async` constructors are not allowed.
- Implement async equivalents for `End`, `Dispose` and `Save` methods on the audit scope.
- Provide async `Create` methods for the audit scope factory.
- Implement async methods on the data providers (file, sql, mongo, mysql, ...) 
- Use the async methods whenever possible on the extensions (EF, webapi, mvc, ...)

**Comment by thepirat000** [comment]
Finally implemented async support on all the data providers and the audit scope actions. Starting from version 11.0.0.

What is new in this version:

- Async support for all the data providers and audit scope actions: Sql, MySql, Postgres, Mongo, Redis, Azure and UDP data providers now fully support async operations.
- Asynchronous dynamic data provider.
- Implemented data retrieval on most of the data providers.
- New custom action OnEventSaved triggered right after the event is saved.
