### ISSUE TITLE
Event ID column type

### ISSUE THREAD

**Issue by Tabgyn** [thepirat000/Audit.NET#85]
Can I change the type of the ID column in the event table?

I would like to use GUID

**Comment by thepirat000** [comment]
What do you mean by event table? Where do you store the audits? Do you use any of the data providers extensions?

**Comment by Tabgyn** [comment]
I am using SqlServer and EntityFramework.

Here is my configuration:
```c#
Audit.Core.Configuration.Setup()
                .UseSqlServer(config => config
                    .ConnectionString(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)
                    .TableName("Event")
                    .IdColumnName("EventId")
                    .JsonColumnName("Data"));

Audit.EntityFramework.Configuration.Setup()
                .ForContext<DbContext>(config => config
                    .IncludeEntityObjects(false)
                    .AuditEventType("{context}:{database}"));
```

Ok, it accepts any type that can be converted to nvarchar, but then I need to extend something for it to use GUID?

And as a suggestion, I'd like to be able to change all the column names, but the InsertedDate column is not possible, I would like to add this option as well as the LastUpdatedDate column. It would be strange to have one part of the table translated and another not.

**Comment by thepirat000** [comment]
As long as it's convertible to NVARCHAR you shouldn't have problems. Do you?

All the names can be configured on the `SqlDataProvider`. There is no mandatory "InsertedDate" column. Note the [`SqlScript.Sql`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.SqlServer/SqlScript.sql) provided is just an example of the table. You can have any name for the inserted date column since they have a default. The only constraints it has, are those mentioned on the documentation:

- The table should exists.
- The table should have a single ID column (Unique or Primary key).
- The type of the ID column should be convertible to NVARCHAR

**Comment by Tabgyn** [comment]
Ok, it was my lack of attention, since the InsertedDate column takes the default value.
Tnks @thepirat000 your framework is incredible.

**Comment by thepirat000** [comment]
Thanks for your comments
