### ISSUE TITLE
Extend AuditBehavior

### ISSUE THREAD

**Issue by ShoshanaTzi** [thepirat000/Audit.NET#88]
Hi,
I need a dynamic behavior in `Audit.WCF`,
That is: one service must to audit to X table, and other service to Y table.
I want them to use in a differents attributes, something like this:

` public class AuditMainApp : AuditBehaviorAttribute
    {
        protected override object CreateBehavior()
        {
            (CurrentAuditScope.DataProvider as SqlDataProvider).TableName = "AuditEvent_App";
            return base.CreateBehavior();
        }
    }`

but the `AuditBehaviorAttribute` is sealed
there is another nice way to do that?

**Comment by thepirat000** [comment]
That's not the way to go. You should not change the tablename of the sql data provider because it will be shared among threads.

You have some ways to accomplish what you want, for example creating a custom data provider that wraps different instances of the sqldataprovider, one for each table.

But since what you're asking sounds familiar, I will better enhance the `SqlDataProvider` to allow changing the parameters dynamically. For example, instead of setting a TableName as a string, you could set a TableNameBuilder that is a function of the audit event, so you can for example use the EventType string field to set the table name:

```C#
    Configuration.Setup().UseSqlServer(config => config
        .TableNameBuilder(ev => ev.EventType)
        ...);
```

And on your service:
```c#
[AuditBehavior(EventType = "Orders")]
public class OrderService : IOrderService
{
  ...
}
```

Will work on this enhancement and let you know.

**Comment by ShoshanaTzi** [comment]
Nice implementation, thank's
(I still like that no needed to specific the table name by programmers, but it's also good)

**Comment by thepirat000** [comment]
No problem, since you will have the event, you could do it by the Contract Name, for example:

```C#
.TableName(ev => ev.GetWcfAuditAction().ContractName == "IOrderService" ? "AuditEvent_App" : "AnotherTable")
```

**Comment by ShoshanaTzi** [comment]
Thanks, in the response abvoe, you wrote the 
```
Configuration.Setup().UseSqlServer(config => config
        .TableNameBuilder(ev => ev.EventType)
        ...);
```
which configuration is it?

**Comment by thepirat000** [comment]
Is not there yet, I'm working on it

**Comment by thepirat000** [comment]
You should be able to use it now, upgrade to version **9.3.0**.

```c#
Audit.Core.Configuration.Setup().UseSqlServer(config => config
        .TableName(ev => ev.EventType)
        ...);
```

Give some minutes to the nuget packages to get indexed.

Feel free to re-open this if you have any issue.

**Comment by ShoshanaTzi** [comment]
Thank's, I test it's now

**Comment by thepirat000** [comment]
You got lucky I was working on this just now 😄 I think I just broke the bugfixing time record... Hope it helps. Regards

**Comment by ShoshanaTzi** [comment]
Working good! Thank's for the most quicly response I got...
